[package]
name = "pydcstrngs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0.90"
tree-sitter = "0.22.2"
tree-sitter-python = "0.21.0"
